// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ChampInfo
{

    public class Altimage
    {


        public string Full { get; set; }


        public string Sprite { get; set; }


        public string Group { get; set; }


        public int X { get; set; }


        public int Y { get; set; }


        public int W { get; set; }

        public int H { get; set; }
    }

}
