// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace ChampInfo
{
    public class ChampDTO
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Blurb { get; set; }
        public string[] Tags { get; set; }
        public Info Info { get; set; }
        public Spell[] Spells { get; set; }
    }
}