// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ChampInfo
{

    public class Info
    {


        public int Attack { get; set; }


        public int Defense { get; set; }


        public int Magic { get; set; }


        public int Difficulty { get; set; }
    }

}
