// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace ChampInfo
{
    public class Leveltip
    {
        public string[] Label { get; set; }
        public string[] Effect { get; set; }
    }
}