// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ChampInfo
{

    public class Leveltip
    {


        public string[] Label { get; set; }

        public string[] Effect { get; set; }
    }

}
