// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ChampInfo
{

    public class Var
    {


        public string Key { get; set; }


        public string Link { get; set; }

        public double[] Coeff { get; set; }
    }

}
