// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace ChampInfo
{
    public class Var
    {
        public string Key { get; set; }
        public string Link { get; set; }
        public double[] Coeff { get; set; }
    }
}